// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type Note struct {
	ID        int32
	Title     string
	Content   string
	CreatedAt sql.NullTime
}
