// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package database

import (
	"context"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (title, content)
VALUES ($1, $2)
RETURNING id, title, content, created_at
`

type CreateNoteParams struct {
	Title   string
	Content string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote, arg.Title, arg.Content)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNoteByID = `-- name: DeleteNoteByID :execrows
DELETE FROM notes WHERE id = $1
`

func (q *Queries) DeleteNoteByID(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNoteByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllNotes = `-- name: GetAllNotes :many
SELECT id, title, content, created_at
FROM notes
ORDER BY id
`

func (q *Queries) GetAllNotes(ctx context.Context) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getAllNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT id, title, content, created_at
FROM notes
WHERE id = $1
`

func (q *Queries) GetNoteByID(ctx context.Context, id int32) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNoteByID, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const updateNoteByID = `-- name: UpdateNoteByID :one
UPDATE notes
SET title = $1, content = $2
WHERE id = $3
RETURNING id, title, content, created_at
`

type UpdateNoteByIDParams struct {
	Title   string
	Content string
	ID      int32
}

func (q *Queries) UpdateNoteByID(ctx context.Context, arg UpdateNoteByIDParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNoteByID, arg.Title, arg.Content, arg.ID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
