version: "3.9"

services:
  postgres:
    image: postgres:17

    container_name: go-notes-db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notesdb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .

    container_name: go-notes-api

    depends_on:
      - postgres

    ports:
      - "8080:8080"

    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/notesdb?sslmode=disable

volumes:
  postgres_data: